name: bump

on:
  schedule:
    - cron: '0 0 * * 3'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - run: bundle install
      - run: rake run

      # create pr if file changed.
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: bump up versions'
          title: '[bot] bump'
          body: 'Automated changes by actions. Please look at file changes.'
          reviewers: enuesaa
          assignees: enuesaa
          branch: bump/patch
          branch-suffix: timestamp
