name: bump

on:
  schedule:
    - cron: '0 0 * * 3' # 水曜0時
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - run: bundle install
      - run: rake run

      # create pr if file changed
      - id: pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: Bump versions'
          title: 'bot: Bump versions'
          body: Automated changes by GitHub Actions
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          branch: bump/patch
          branch-suffix: timestamp

      - if: steps.pr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --merge --delete-branch $PR_NUMBER
        env:
          PR_NUMBER: ${{ steps.pr.outputs.pull-request-number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
